services:

    #Nginx Service
    recipe-nginx:
        build:
            context: ./src/nginx
            dockerfile: Dockerfile
        image: recipe-nginx
        container_name: recipe-nginx
        restart: unless-stopped
        ports:
            - "82:80"
            - "446:443"
        volumes:
            - ./src/nginx:/var/www/public
            - ./volume/config/nginx/conf.d/local:/etc/nginx/conf.d
            - ./volume/config/nginx/ssl/local:/etc/nginx/ssl
        networks:
            - recipe-network

    #PHP Service
    recipe-php:
        build:
            context: ./src/php
            dockerfile: Dockerfile
        image: recipe-php
        container_name: recipe-php
        restart: unless-stopped
        ports:
            - "9002:9000"
        volumes:
            - ./src/php:/var/www
            - ./volume/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./volume/config/laravel/env/local/.env:/var/www/.env
            - ./volume/config/laravel/supervisor/local/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./volume/logs/laravel:/var/www/storage/logs
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
        networks:
            - recipe-network

    #MySQL Service
    recipe-mysql:
        image: mysql:5.7.32
        container_name: recipe-mysql
        restart: unless-stopped
        ports:
            - "4308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootPassword@1
            MYSQL_DATABASE: recipe
            MYSQL_USER: recipe
            MYSQL_PASSWORD: passWord@1
        volumes:
            - ./volume/config/mysql/my.cnf:/etc/mysql/my.cnf
            - ./volume/data/mysql:/var/lib/mysql
        networks:
            - recipe-network

    #Memcached Service
    recipe-memcached:
        image: memcached:1.6.17-alpine
        container_name: recipe-memcached
        restart: unless-stopped
        ports:
            - '11214:11211'
        networks:
            - recipe-network

    #Redis Service
    recipe-redis:
        image: redis:6.2.6-alpine
        container_name: recipe-redis
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6381}:6379'
        volumes:
            - ./volume/data/redis:/data
        networks:
            - recipe-network

#Docker Networks
networks:
    recipe-network:
         name: recipe-network
         external: true
